config/routes.rb
Rails.application.routes.draw do

  # devise_for :customers
  devise_for :customers, skip: [:passwords],  controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admins,skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
}


   namespace :admin do
    root 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :rooms, only: [:index, :show, :edit, :new, :create, :update]
    resources :lendings, only: [:index, :show, :edit, :new, :create, :update]
    resources :reservations, only: [ :index, :show, :update]
  end

   scope module: :public do
    root 'homes#top'
    get 'about', to: 'homes#about'
    resource :customers, only: [:show,:edit, :update]
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/out' => 'customers#out', as: 'out'
    get 'reservations/thanx'
    post 'reservations/check'
    resources :reservations, only: [ :index,:edit, :new, :create, :destroy]
    resources :rooms, only: [:index, :show]
    resources :lendings, only: [:index, :show]
   end

   get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations
end

app/models/lending.rb
class Lending < ApplicationRecord
  has_many :reservations

  def self.looks(search, word)
    if search == "perfect_match"
      @lending = Lending.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @lending = Lending.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @lending = Lending.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @lending = Lending.where("name LIKE?","%#{word}%")
    else
      @room = Room.all
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
  belongs_to :lending
  belongs_to :room

  #enum quantity: { one: 0, two: 1, three: 2 }

  validate :duplicate_check

  def duplicate_check
    if Reservation.where('room_id = ? AND finish > ? AND ? > start', self.room_id, self.start, self.finish).present?
      errors.add(:start, "NG")
      errors.add(:finish, "NG")
    end
  end
end

app/models/reservation_lending.rb
class ReservationLending < ApplicationRecord
  belongs_to :reservation
  belongs_to :lending
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations

  def self.looks(search, word)
    if search == "perfect_match"
      @room = Room.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @room = Room.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @room = Room.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @room = Room.where("name LIKE?","%#{word}%")
    else
      @lending = Lending.all
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

 private

  def customer_params
    params.require(:customer).permit(:email, :sur_name, :first_name, :sur_name_kana, :first_name_kana, :post_code, :address, :phone_number, :is_removed)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/lendings_controller.rb
class Admin::LendingsController < ApplicationController

  def index
    @lendings = Lending.all
  end

  def show
    @lending = Lending.find(params[:id])
  end

  def new
    @lending_new = Lending.new
  end

  def create
    @lending_new = Lending.new(lending_params)
    @lending_new.save
    redirect_to admin_lending_path(@lending_new)
  end

  def edit
    @lending = Lending.find(params[:id])
  end

  def update
    lending = Lending.find(params[:id])
    lending.update(lending_params)
    redirect_to admin_lending_path(lending.id)
  end

  private

  def lending_params
    params.require(:lending).permit(:name,:quantity, :caption)
  end

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
   def index
    @rooms = Room.all
   end

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room_new = Room.new
  end

  def create
    @room_new = Room.new(room_params)
    @room_new.save
    redirect_to admin_room_path(@room_new)
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    room = Room.find(params[:id])
    room.update(room_params)
    redirect_to admin_room_path(room.id)
  end

  private

  def room_params
    params.require(:room).permit( :name, :caption)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    admin_reservations_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]

    if @range == "Room"
      @rooms = Room.looks(params[:search], params[:word])
    else 
      @selected_range = "Lending"
      @lendings = Lending.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/lendings_helper.rb
module Admin::LendingsHelper
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/customers/_show.html.erb
 <div class="field">
    <span>名前</span>
    （姓）<%= customer.sur_name %>
    （名）<%= customer.first_name %>
  </div>

  <div class="field">
    <span>フリガナ</span>
    （セイ）<%= customer.sur_name_kana %>
    （メイ）<%= customer.first_name_kana %>
  </div>

  <div class="field">
    <span>メールアドレス</span>
    <%= customer.email %>
  </div>

  <div class="field">
    <span>郵便番号</span>
    <%= customer.post_code %>
  </div>

  <div class="field">
    <span>住所</span>
    <%= customer.address %>
  </div>

  <div class="field">
    <span>電話番号</span>
    <%= customer.phone_number %>
  </div>

  <% if @customer.is_removed %>
    退会
  <% else %>
    有効
  <% end %>

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <h2>会員情報編集</h2>


      <%= form_with model: @customer, url: admin_customer_path do |f| %>

        <div class="field">
          <%= f.label :名前 %>
          （姓）<%= f.text_field :sur_name %>
          （名）<%= f.text_field :first_name %>
        </div>

        <div class="field">
          <%= f.label :フリガナ %>
          （セイ）<%= f.text_field :sur_name_kana %>
          （メイ）<%= f.text_field :first_name_kana %>
        </div>

        <div class="field">
          <%= f.label :メールアドレス %>
          <%= f.email_field :email, autocomplete: "email" %>
        </div>

        <div class="field">
          <%= f.label :郵便番号（ハイフンなし） %>
          <%= f.text_field :post_code %>
        </div>

        <div class="field">
          <%= f.label :住所 %>
          <%= f.text_field :address %>
        </div>

        <div class="field">
          <%= f.label :電話番号（ハイフンなし） %>
          <%= f.text_field :phone_number %>
        </div>

        <div class="field">
          <%= f.select :is_removed, [['退会', true], ['有効', false]] %>
        </div>

        <div class="actions">
          <%= f.submit "編集内容を保存", class:"btn btn-primary" %>
        </div>
      <% end %>

      <%= link_to "会員情報に戻る", admin_customer_path(@customer),  class:"btn btn-info"%>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
   <div class="row">
     <div class="col-xs-5">
      <h2>会員一覧</h2><br><br>
      <table class="table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td>
              <%= customer.id %>
            </td>
            <td>
              <%= link_to admin_customer_path(customer) do %>
              <%= customer.sur_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td>
              <%= customer.email %>
            </td>
            <td>
              <% if customer.is_removed  %>
                退会
              <% else %>
                有効
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8">

            <h2><%= @customer.sur_name %><%= @customer.first_name %>さんの会員情報</h2>
            <br>
            <br>
            <%= render 'show', customer: @customer %>
            <br>

            <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %>
             <br>


    </div>
  </div>
 </div>

app/views/admin/lendings/edit.html.erb
<div class="container">
   <div class="row" >
     <div class="col-xs-4">
        <h1>部屋編集</h1>
        <%= form_with model: @lending, url: admin_lending_path, method: :patch do |f| %>


        <h4>貸出物名</h4>
           <%= f.text_field :name %>
         <h4>個数</h4>
           <%= f.text_field :quantity %>
        <h4>貸出物説明</h4>
           <%= f.text_area :caption %>

        <br>
        <br>

        <%= f.submit '変更を保存', class:"btn btn-primary" %>

        <% end %>
     </div>
  </div>
</div>

app/views/admin/lendings/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-xs-12">

     <h1>貸出物一覧</h1>

     <%= link_to new_admin_lending_path do %>
      <i class="fas fa-plus-circle"></i>
     <% end %>

     <table class="table">
        <thead class="table-light">
         <tr>
          <th>貸出物ID</th>
          <th>貸出物名</th>
          <th>説明</th>
         </tr>
       </thead>

       <tbody>
        <% @lendings.each do |lending| %>
        <tr>
         <td><%= lending.id %></td>

         <td><%= link_to lending.name, admin_lending_path(lending) %></td>

         <td><%= lending.caption %></td>
        </tr>
        <% end %>
       </tbody>


  </div>
 </div>
</div>

app/views/admin/lendings/new.html.erb
<div class="container">

    <div class="row">

      <div class="col-xs-12">
        <h1>貸出物新規登録</h1>
        <%= form_with model: @lending_new, url: admin_lendings_path, method: :post do |f| %>

        　　　<div class="form-group">
                <h4>貸出物名</h4>
                   <%= f.text_field :name %>
            </div>

            　<div class="form-group">
                <h4>個数</h4>
                   <%= f.text_field :quantity %>
            </div>

            <div class="form-group">
                <h4>貸出物の説明</h4>
                   <%= f.text_area :caption %>
            </div>

            <%= f.submit '新規登録', class:"btn btn-success" %>

        <% end %>

      </div>
    </div>
</div>

app/views/admin/lendings/show.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-xs-12">

      <h1>貸出物詳細</h1><br>
      　<div class="col-xs-6">
      　   <div class="field">
             <h4>貸出物名</h4>
             <p><%= @lending.name %></p>
          </div>
           <div class="field">
             <h4>個数</h4>
             <p><%= @lending.quantity %></p>
          </div>
        　<div class="field">
             <h4>貸出物説明</h4>
             <p><%= @lending.caption %></p>
        　</div>
          <div class="field">
             <span><%= link_to "編集する",edit_admin_lending_path(@lending), class:"btn btn-success" %></span>
          </div>
        </div>
     </div>
  </div>
</div>

app/views/admin/rooms/edit.html.erb
<div class="container">
   <div class="row" >
     <div class="col-xs-4">
        <h1>部屋編集</h1>
        <%= form_with model: @room, url: admin_room_path, method: :patch do |f| %>
        
        
        <h4>商品名</h4>
           <%= f.text_field :name %>
        <h4>商品説明</h4>
           <%= f.text_area :caption %>
       
        <br>
        <br>
        
        <%= f.submit '変更を保存', class:"btn btn-primary" %>
        
        <% end %>
     </div>
  </div>
</div>

app/views/admin/rooms/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-xs-12">

     <h1>部屋一覧</h1>

     <%= link_to new_admin_room_path do %>
      <i class="fas fa-plus-circle"></i>
     <% end %>

     <table class="table">
        <thead class="table-light">
         <tr>
          <th>部屋ID</th>
          <th>部屋名</th>
          <th>説明</th>
         </tr>
       </thead>

       <tbody>
        <% @rooms.each do |room| %>
        <tr>
         <td><%= room.id %></td>

         <td><%= link_to room.name, admin_room_path(room) %></td>

         <td><%= room.caption %></td>
        </tr>
        <% end %>
       </tbody>


  </div>
 </div>
</div>

app/views/admin/rooms/new.html.erb
<div class="container">
    
    <div class="row">
        
      <div class="col-xs-12">
        <h1>部屋新規登録</h1>
        <%= form_with model: @room_new, url: admin_rooms_path, method: :post do |f| %>
        
        　　　<div class="form-group">
                <h4>部屋名</h4>
                   <%= f.text_field :name %>
            </div>
            
            <div class="form-group">
                <h4>部屋の説明</h4>
                   <%= f.text_area :caption %>
            </div>
            
            <%= f.submit '新規登録', class:"btn btn-success" %>
            
        <% end %>
        
      </div>
    </div>
</div>

app/views/admin/rooms/show.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-xs-12">

      <h1>部屋詳細</h1><br>
      　<div class="col-xs-6">
      　   <div class="field">
             <h4>部屋名</h4>
             <p><%= @room.name %></p>
          </div>
        　<div class="field">
             <h4>部屋説明</h4>
             <p><%= @room.caption %></p>
        　</div>
          <div class="field">
             <span><%= link_to "編集する",edit_admin_room_path(@room), class:"btn btn-success" %></span>
          </div>
        </div>
     </div>
  </div>
</div>