config/routes.rb
Rails.application.routes.draw do

  # devise_for :customers
  devise_for :customers, skip: [:passwords],  controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admins,skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
}


   namespace :admin do
    root 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :rooms, only: [:index, :show, :edit, :new, :create, :update]
    resources :lendings, only: [:index, :show, :edit, :new, :create, :update]
    resources :reservations, only: [ :index, :show, :update]
  end

   scope module: :public do
    root 'homes#top'
    get 'about', to: 'homes#about'
    resource :customers, only: [:show,:edit, :update]
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/out' => 'customers#out', as: 'out'
    get 'reservations/thanx'
    post 'reservations/check'
    resources :reservations, only: [ :index,:edit, :new, :create, :destroy]
    resources :rooms, only: [:index, :show]
    resources :lendings, only: [:index, :show]
   end

   get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations
end

app/models/lending.rb
class Lending < ApplicationRecord
  has_many :reservations

  def self.looks(search, word)
    if search == "perfect_match"
      @lending = Lending.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @lending = Lending.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @lending = Lending.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @lending = Lending.where("name LIKE?","%#{word}%")
    else
      @room = Room.all
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
  belongs_to :lending
  belongs_to :room

  #enum quantity: { one: 0, two: 1, three: 2 }

  validate :duplicate_check

  def duplicate_check
    if Reservation.where('room_id = ? AND finish > ? AND ? > start', self.room_id, self.start, self.finish).present?
      errors.add(:start, "NG")
      errors.add(:finish, "NG")
    end
  end
end

app/models/reservation_lending.rb
class ReservationLending < ApplicationRecord
  belongs_to :reservation
  belongs_to :lending
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations

  def self.looks(search, word)
    if search == "perfect_match"
      @room = Room.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @room = Room.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @room = Room.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @room = Room.where("name LIKE?","%#{word}%")
    else
      @lending = Lending.all
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/lendings_controller.rb
class Admin::LendingsController < ApplicationController

  def index
    @lendings = Lending.all
  end

  def show
    @lending = Lending.find(params[:id])
  end

  def new
    @lending_new = Lending.new
  end

  def create
    @lending_new = Lending.new(lending_params)
    @lending_new.save
    redirect_to admin_lending_path(@lending_new)
  end

  def edit
    @lending = Lending.find(params[:id])
  end

  def update
    lending = Lending.find(params[:id])
    lending.update(lending_params)
    redirect_to admin_lending_path(lending.id)
  end

  private

  def lending_params
    params.require(:lending).permit(:name,:quantity, :caption)
  end

end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
   def index
    @rooms = Room.all
   end

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room_new = Room.new
  end

  def create
    @room_new = Room.new(room_params)
    @room_new.save
    redirect_to admin_room_path(@room_new)
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    room = Room.find(params[:id])
    room.update(room_params)
    redirect_to admin_room_path(room.id)
  end

  private

  def room_params
    params.require(:room).permit( :name, :caption)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]

    if @range == "Room"
      @rooms = Room.looks(params[:search], params[:word])
    else 
      @selected_range = "Lending"
      @lendings = Lending.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/lendings_helper.rb
module Admin::LendingsHelper
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header class="shadow">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to root_path do %><i class="fas fa-network-wired"></i>TOP<% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="row">
      <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <% if customer_signed_in? %>
        <%# if true %>
          <li>
            <%= link_to  customers_path, class: 'nav-link text-light' do %>
             <i class="fas fa-users"></i>マイページ
            <% end %>
          </li>
          <li>
            <%= link_to  rooms_path,class: 'nav-link text-light' do  %>
             <i class="fas fa-door-closed"></i>部屋一覧
            <% end %>
          </li>
           <li>
            <%= link_to  lendings_path,class: 'nav-link text-light' do  %>
             <i class="fas fa-tv"></i>貸出物一覧
            <% end %>
          </li>
          <li>
            <%= link_to  new_reservation_path,class: 'nav-link text-light' do  %>
            <i class="fas fa-check"></i>予約ページ
            <% end %>
          </li>
          <li>
            <%= link_to  destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
            <%#= link_to "ログアウト", root_path %>
          </li>


        <% elsif admin_signed_in? %>
          <li>
            <%= link_to  admin_customers_path, class: 'nav-link text-light' do %>
             <i class="fas fa-users"></i>会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to  admin_reservations_path, class: 'nav-link text-light' do %>
             <i class="fas fa-check"></i>予約一覧
            <% end %>
          </li>
          <li>
             <%= link_to  admin_rooms_path, class: 'nav-link text-light' do %>
              <i class="fas fa-door-closed"></i>部屋一覧
             <% end %>
          </li>
           <li>
             <%= link_to  admin_lendings_path, class: 'nav-link text-light' do %>
              <i class="fas fa-tv"></i>貸出物一覧
             <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>


        <% else %>
          <li>
          　<%= link_to  about_path,class: 'nav-link text-light' do %>
          　<i class="fas fa-link"></i>About
          　<% end %>
          </li>
          <li>
　　　　　　<%= link_to  rooms_path,class: 'nav-link text-light' do %>
　　　　　　 <i class="fas fa-door-closed"></i>部屋一覧
　　　　　　<% end %>
          </li>
          <li>
　　　　　　<%= link_to  lendings_path,class: 'nav-link text-light' do %>
　　　　　　 <i class="fas fa-tv"></i>貸出物一覧
　　　　　　<% end %>
          </li>
          <li>
　　　　　　<%= link_to  new_customer_registration_path,class: 'nav-link text-light' do %>
　　　　　　 <i class="fas fa-user-plus"></i>新規登録
　　　　　　<% end %>
          </li>
          <li>
　　　　　　<%= link_to  new_customer_session_path,class: 'nav-link text-light' do %>
　　　　　　 <i class="fas fa-sign-in-alt"></i>ログイン
　　　　　　<% end %>
          </li>
        <% end %>
        </ul>
      </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rental</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
     <main>
     <div class="d-flex justify-content-center mb-2">
    <%= render partial: "searches/search", locals: { selected_range: @selected_range }%>
    </div>
    <%= yield %>
    </main>
  </body>
</html>